### ISSUE TITLE
打开黑屏

### ISSUE THREAD

**Issue by xiaozhou1210** [jayjd/HuYaTv#1]
海信安卓4.4打开黑屏，怀疑解码器问题，有声音有弹幕没画面

**Comment by jayjd** [comment]
出现黑屏概率有多少？

**Comment by xiaozhou1210** [comment]
> 出现黑屏概率有多少？

刚试了一下19版本，画面100%黑屏，弹幕滚动、声音都是正常的，不知道什么原因，海信电视安卓4.4.2

**Comment by jayjd** [comment]
应该是解码问题 后续修复吧！

**Comment by jayjd** [comment]
> > 出现黑屏概率有多少？
> 
> 刚试了一下19版本，画面100%黑屏，弹幕滚动、声音都是正常的，不知道什么原因，海信电视安卓4.4.2

最新版本已经加入自选解码
