### ISSUE TITLE
打开直播，第一时间黑屏，需要大概10秒才能正常播放

### ISSUE THREAD

**Issue by adzcsx2** [jayjd/HuYaTv#12]
这个能修复吗？
还有打开app也是第一时间黑屏，应该是加载github的那个初始化文件太慢，希望能优化一下这部分体验。

**Comment by jayjd** [comment]
用的GitHub直链

**Comment by adzcsx2** [comment]
我知道，github在国内解析速度太慢了。希望能优化一下
