### ISSUE TITLE
用exo解码的时候切清晰度会出现没声音

### ISSUE THREAD

**Issue by lsclh** [jayjd/HuYaTv#13]
用exo切清晰度没声音了 再切到系统解码或者ijk就又有声音了 再切回exo有时候声音能恢复 有时候不能 大多数时候不能 电视是华为智慧屏v75

**Comment by jayjd** [comment]
选择合适的解码方式 不一定exo就是最好的

**Comment by akarrin** [comment]
> 选择合适的解码方式 不一定exo就是最好的

选择其他解码方式后，一定概率会出现直接退出直播间的情况，并提示"播放完毕"，且必须改回exo才能继续观看

**Comment by jayjd** [comment]
> > 选择合适的解码方式 不一定exo就是最好的
> 
> 选择其他解码方式后，一定概率会出现直接退出直播间的情况，并提示"播放完毕"，且必须改回exo才能继续观看

已经开始开发2.0版本了   会一并解决之前的问题 并加入抖音直播
