### ISSUE TITLE
二级菜单遥控器点不了

### ISSUE THREAD

**Issue by lirenxd** [jayjd/HuYaTv#15]
一起看里面的二级菜单电视遥控器点不了，小米电视
![二级菜单](https://github.com/jayjd/HuYaTv/assets/107117921/70df7e02-6fc9-4655-98a4-3cd9fb269bc9)
![二级菜单2](https://github.com/jayjd/HuYaTv/assets/107117921/dc0e8398-c5aa-49a2-8fe0-dd1f989fd020)

**Comment by jayjd** [comment]
在解决了  在高版本是可以获得焦点的
