### ISSUE TITLE
播放一段时间后卡死

### ISSUE THREAD

**Issue by ruikai0103** [jayjd/HuYaTv#16]
小米电视，播放大概一小时后。画面会持续卡顿。直到最后电视卡死，遥控器无反应，米家提示电视已经掉线了！只能拔电源重启。

**Comment by zzfeed** [comment]
创维电视也一样，播放几分钟就卡住了，需要退出再进入，android版本为5.1，请大佬改进下

**Comment by jayjd** [comment]
建议切换下清晰度和解码方式

**Comment by ruikai0103** [comment]
> 建议切换下分析和解码方式

切换后还是不行，补充一下  画面开始卡的时候遥控器就失效了  但是画面会播放，卡顿也是从大概10秒卡一下  变成5秒卡一下  就是时间越来越短  最后直接卡死。  但是发现卡的时候 遥控器已经按不了。。
