### ISSUE TITLE
tcl电视，切换到抖音平台无显示。

### ISSUE THREAD

**Issue by hocoo** [jayjd/HuYaTv#19]
tcl电视，切换到抖音平台无显示。屏幕闪一下进入背景色不动了。

**Comment by jayjd** [comment]
下载最新版本 试试吧
[https://github.com/jayjd/HuYaTv/releases/download/2.0.3/HuYa-2.0.3-20240201.apk](url)

**Comment by hocoo** [comment]
使用最新版，一台tcl 55V6E，切换抖音无显示。一台tcl 75t8g正常。

**Comment by U188** [comment]
我也是
