### ISSUE TITLE
创维电视，安卓7，安装后无画面

### ISSUE THREAD

**Issue by bzlzm** [jayjd/HuYaTv#2]
创维电视，应该是安卓7，反正是主流创维系统，系统更新过的，电视也是这几年的新电视机，
安装后有声音，有字幕，但无画面，貌似是解码的问题
早先1.15版本是可以播放的，后来版本升级后打开APP必须要升级才能播放，但电视不能在线升级，所以下载新的1.20到U盘安装后就画面了。

**Comment by bzlzm** [comment]
1.0.21版仍无画面

**Comment by bzlzm** [comment]
1.0.22版仍然是有声音、字幕，无图像。

**Comment by jayjd** [comment]
@bzlzm 收到你的反馈了 下个版本 会加上解码选择  应该会好点。

**Comment by bzlzm** [comment]
> @bzlzm 收到你的反馈了 下个版本 会加上解码选择 应该会好点。

1.0.23 更换解码方式后可以播放了，但是画面质量太差了，像慢动作，是不是软件内存战胜或缓存要求空间高？同样的机器里装有BLBL_release_v1.4.0 很流畅，谢谢！

**Comment by jayjd** [comment]
> > @bzlzm 收到你的反馈了 下个版本 会加上解码选择 应该会好点。
> 
> 1.0.23 更换解码方式后可以播放了，但是画面质量太差了，像慢动作，是不是软件内存战胜或缓存要求空间高？同样的机器里装有BLBL_release_v1.4.0 很流畅，谢谢！ BLBL地址：https://github.com/xiaye13579/BBLL

@bzlzm 正在调整渲染方式
