### ISSUE TITLE
虎牙直播騰訊線路會閃退，其他線路都不能看了

### ISSUE THREAD

**Issue by chenhy22tw** [jayjd/HuYaTv#22]
虎牙直播騰訊線路會閃退，其他線路都不能看了 ，出現2004-ERROR_CODE_IO_BAD_HTTP_STATUS,請切換其他線路的錯誤，請修正，謝謝。

**Comment by chenhy22tw** [comment]
2.1.0 版，虎牙直播都不能看了，請修復，謝謝

**Comment by lsclh** [comment]
我也是这样 直接看不见了

**Comment by chenhy22tw** [comment]
希望你有看到我的回饋

**Comment by chenhy22tw** [comment]
有空回覆一下，謝謝

**Comment by chenhy22tw** [comment]
纯粹直播，1.5.8 版，已解决了这个问题了，https://github.com/liuchuancong/pure_live，提供给你参考

**Comment by chenhy22tw** [comment]
抱歉，純粹直播1.5.8 版，還是有問題

**Comment by jayjd** [comment]
@lsclh 已经修复 测试中。 预计晚上发布
