### ISSUE TITLE
2.1.1版首页当中，王者荣耀版块，点击张大仙，提示未开播。

### ISSUE THREAD

**Issue by forseticn** [jayjd/HuYaTv#25]
2.1.1版首页当中，王者荣耀版块，点击张大仙，提示未开播。
实际在切换到抖音后，张大仙是在直播状态的。
可能是更新后首页上张大仙这个链接没有对应更新我猜。
其它人的没有一一测试，
最后，感谢作者的付出。

**Comment by jayjd** [comment]
@forseticn 要在抖音界面找张大仙 或者在最顶部点击张大仙  在虎牙界面点击张大仙 是不行的

**Comment by forseticn** [comment]
> @forseticn 要在抖音界面找张大仙 或者在最顶部点击张大仙 在虎牙界面点击张大仙 是不行的

好的 明白了 我记得上个版本是可以直接点播放的
