### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by drw2005** [jayjd/HuYaTv#3]
一、最上面的版块太多了，大家各有感兴趣的版块，能不能：
1、可以自定义只显示自己的喜欢的版块？其他的隐藏。
2、可以自定义版块显示顺序，把自己喜欢的版块调整到前面来。
以上两个功能，能都实现最好。

二、发现向下翻很多页后，无法快速返回到最上面的版块，只能原路上翻，很麻烦。希望按一下遥控器的返回键，能直接返回上面的版块。（比如，按一下返回键，回到小版块，再按一下返回到大版块）
![](https://ru.iytc.net/i/2023/06/29/dj6cfm.png)

最后，感谢的大佬的软件，很好用。

**Comment by jayjd** [comment]
@drw2005 收到你的反馈了  第二大项 下个版本就能弄好 
下个版本还会加上直播解码选择  第一大项的话 改动比较大 暂不考虑（可能会换一种方式去做优化）
