### ISSUE TITLE
不能白嫖啊

### ISSUE THREAD

**Issue by 17663081373** [jayjd/HuYaTv#30]

**Comment by jayjd** [comment]
可以  仔细看Live Pro界面的内容

**Comment by iknowzxc** [comment]
> @17663081373 可以 仔细看Live Pro界面的内容

最新版本似乎有问题，旧版本可以

**Comment by jayjd** [comment]
> > @17663081373 可以 仔细看Live Pro界面的内容
> 
> 最新版本似乎有问题，旧版本可以

并没有问题 多尝试看看吧

**Comment by iknowzxc** [comment]
> > > @17663081373 可以 仔细看Live Pro界面的内容
> > 
> > 
> > 最新版本似乎有问题，旧版本可以
> 
> 并没有问题 多尝试看看吧

2.1.12 ok了
