### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by li5bo5** [jayjd/HuYaTv#31]
大佬开发的这个软件已经很牛了！我现在电视上看直播只用这个，
提出一点小建议，望大佬可以考虑。
1、优化缓存，在个别机型上，播放时间太久容易卡顿，尤其是小内存的机型
2、顶部菜单优化，“一直不懂那个张大仙是个什么。。。。”
3、建议：增加刷新机制，如果在某一个一级、或二级标签上长按确定键，则刷新直播间列表，现在打开app的时候没有开播，只能退出app，才可以刷新出新开播的直播间
4、建议：在直播界面按左键，显示收藏夹；这个功能会非常实用！！

**Comment by jayjd** [comment]
> 大佬开发的这个软件已经很牛了！我现在电视上看直播只用这个， 提出一点小建议，望大佬可以考虑。 1、优化缓存，在个别机型上，播放时间太久容易卡顿，尤其是小内存的机型 2、顶部菜单优化，“一直不懂那个张大仙是个什么。。。。” 3、建议：增加刷新机制，如果在某一个一级、或二级标签上长按确定键，则刷新直播间列表，现在打开app的时候没有开播，只能退出app，才可以刷新出新开播的直播间 4、建议：在直播界面按左键，显示收藏夹；这个功能会非常实用！！

1.尽量优化
2.软件开发初衷就是为了看张大仙直播
3.后续版本增加刷新的功能吧
4.现在已经有这个功能了，虎牙直播会显示猜你喜欢，其他直播平台显示的收藏夹的内容
@li5bo5

**Comment by li5bo5** [comment]
> > 大佬开发的这个软件已经很牛了！我现在电视上看直播只用这个， 提出一点小建议，望大佬可以考虑。 1、优化缓存，在个别机型上，播放时间太久容易卡顿，尤其是小内存的机型 2、顶部菜单优化，“一直不懂那个张大仙是个什么。。。。” 3、建议：增加刷新机制，如果在某一个一级、或二级标签上长按确定键，则刷新直播间列表，现在打开app的时候没有开播，只能退出app，才可以刷新出新开播的直播间 4、建议：在直播界面按左键，显示收藏夹；这个功能会非常实用！！
> 
> 1.尽量优化 2.软件开发初衷就是为了看张大仙直播 3.后续版本增加刷新的功能吧 4.现在已经有这个功能了，虎牙直播会显示猜你喜欢，其他直播平台显示的收藏夹的内容 @li5bo5

拜谢大佬！！
