### ISSUE TITLE
2.18.4版本目前无法在最新的小米电视澎湃OS上使用

### ISSUE THREAD

**Issue by bingqingpeng** [jayjd/HuYaTv#33]
安卓版本为14，APP无法获取设备存储权限，直接打不开

**Comment by jayjd** [comment]
是否可以拍个视频
我在安卓14电视模拟器可以正常运行

**Comment by bingqingpeng** [comment]
https://github.com/user-attachments/assets/8f371318-6459-448a-b2b2-7e8e4cc4dd82
刚拍视频的时候没有显示无法获取存储权限了，但还是会卡在启动界面

**Comment by bingqingpeng** [comment]
> 是否可以拍个视频 也可以加QQ频道 方便交流 @bingqingpeng 我在安卓14电视模拟器可以正常运行

https://github.com/user-attachments/assets/8f371318-6459-448a-b2b2-7e8e4cc4dd82
刚拍视频的时候没有显示无法获取存储权限了，但还是会卡在启动界面

**Comment by jayjd** [comment]
> > 是否可以拍个视频 也可以加QQ频道 方便交流 @bingqingpeng 我在安卓14电视模拟器可以正常运行
> 
> https://github.com/user-attachments/assets/8f371318-6459-448a-b2b2-7e8e4cc4dd82 刚拍视频的时候没有显示无法获取存储权限了，但还是会卡在启动界面

检查一下网络 或者手机开热点试试

**Comment by bingqingpeng** [comment]
> > > 是否可以拍个视频 也可以加QQ频道 方便交流 @bingqingpeng 我在安卓14电视模拟器可以正常运行
> > 
> > 
> > https://github.com/user-attachments/assets/8f371318-6459-448a-b2b2-7e8e4cc4dd82 刚拍视频的时候没有显示无法获取存储权限了，但还是会卡在启动界面
> 
> 刚测试 确实有问题 已经调整测试版发频道了

已使用新版本测试，现在可以正常进去了
