### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Miyagi-jiye** [jayjd/HuYaTv#4]
Tab栏分区选项卡不要刚聚焦就切换页面，应该再次点击后才切换页面，不然切换分区的时候就会多次触发页面的重载，挺浪费性能的

**Comment by drw2005** [comment]
是有这个问题，容易造成卡顿。

**Comment by jayjd** [comment]
@Miyagi-jiye @drw2005 收到你们的反馈了  正在调整中。。。
