### ISSUE TITLE
能否去除强制更新，或者自动更新能够更新好。

### ISSUE THREAD

**Issue by NBXianYu** [jayjd/HuYaTv#9]
今年的新电视，TCL的，用U盘安装上之后，打开如果强制更新的话，就会安装包解析失败，只有重新卸载了，下载到U盘里面去安装最新的，还是挺麻烦得。

如果能自动更新更新成功就很好。或者可以设置不自动更新。

**Comment by adzcsx2** [comment]
确实！电视更新app很麻烦，目前功能很稳定不需要更新。

**Comment by adzcsx2** [comment]
> 确实！电视更新app很麻烦，目前功能很稳定不需要更新。

或者需要初始化之前更新，不然手动下载太麻烦了
